export class CommonConstants {
  static readonly FULL_WIDTH: string = '100%';
  static readonly FULL_HEIGHT: string = '100%';
  static readonly INDEX_CONTENT_WIDTH: string = '91.1%';
  static readonly BORDER_RADIUS_INDEX_LIST: number = 18;
  static readonly CARD_TITLE_HEIGHT: number = 20;
  static readonly CARD_TEXT_HEIGHT: number = 48;
  static readonly REFRESH_COUNT: number = 100;
  static readonly LOAD_MORE_COUNT: number = 20;
  static readonly SECTION1_ITEM_SIZE: number = 170;
  static readonly SECTION2_ITEM_SIZE: number = 100;
  static readonly SECTION3_ITEM_SIZE: number = 200;
  static readonly SECTION4_ITEM_SIZE: number = 250;
}